"""add_case_activities_table

Revision ID: 06cceeb5a364
Revises: 
Create Date: 2025-10-21 00:18:23.167646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06cceeb5a364'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('analyst_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('NOTE', 'FINDING', 'EVIDENCE', 'INTERVIEW', 'ANALYSIS', 'ACTION', 'MEETING', 'COMMUNICATION', 'TASK', 'UPDATE', 'MILESTONE', 'OBSERVATION', 'RECOMMENDATION', 'DECISION', 'OTHER', name='activitytype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED', name='activitystatus'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('evidence_links', sa.JSON(), nullable=True),
    sa.Column('related_content_ids', sa.JSON(), nullable=True),
    sa.Column('related_source_ids', sa.JSON(), nullable=True),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('include_in_report', sa.Boolean(), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=True),
    sa.Column('visibility_level', sa.String(length=20), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('edited_by_id', sa.Integer(), nullable=True),
    sa.Column('edit_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['system_users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['edited_by_id'], ['system_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_activities_analyst_id'), 'case_activities', ['analyst_id'], unique=False)
    op.create_index(op.f('ix_case_activities_case_id'), 'case_activities', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_activities_case_id'), table_name='case_activities')
    op.drop_index(op.f('ix_case_activities_analyst_id'), table_name='case_activities')
    op.drop_table('case_activities')
    # ### end Alembic commands ###

