"""initial schema from models

Revision ID: d8729531dd5d
Revises: 
Create Date: 2025-10-20 20:49:02.639595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8729531dd5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_content_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'content_id', name='uq_case_content')
    )
    op.create_index(op.f('ix_case_content_links_case_id'), 'case_content_links', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_content_links_content_id'), 'case_content_links', ['content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_content_links_content_id'), table_name='case_content_links')
    op.drop_index(op.f('ix_case_content_links_case_id'), table_name='case_content_links')
    op.drop_table('case_content_links')
    # ### end Alembic commands ###

